-- AlterTable
ALTER TABLE "Maintenance" ALTER COLUMN "pre_scm_summary_total_count" SET DEFAULT 0,
ALTER COLUMN "post_scm_summary_total_count" SET DEFAULT 0,
ALTER COLUMN "pre_cm_partial" SET DEFAULT 0,
ALTER COLUMN "post_cm_partial" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_total_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_total_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_erouter_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_erouter_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_cpe_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_cpe_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_edva_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_edva_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_emta_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_emta_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_estb_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_estb_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_d4_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_d4_count" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_d6_count" SET DEFAULT 0,
ALTER COLUMN "post_cpe_d6_count" SET DEFAULT 0,
ALTER COLUMN "pre_scm_summary_total" SET DEFAULT 0,
ALTER COLUMN "post_scm_summary_total" SET DEFAULT 0,
ALTER COLUMN "pre_rpd" SET DEFAULT 0,
ALTER COLUMN "post_rpd" SET DEFAULT 0,
ALTER COLUMN "pre_cpe_exclude_d4d6" SET DEFAULT 0,
ALTER COLUMN "post_cpe_exclude_d4d6" SET DEFAULT 0;
